name: Backup Repo S3
on:
  schedule:
        - cron: '0 0 * * 1'
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1.1.1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          MIRROR_TARGET: backup-git-trinks-prd/${{ github.event.repository.name }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_PROD }}
        with:
          args: --overwrite --remove
  
  notificar:
    needs: s3Backup
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Enviar notificação simples via SNS
        run: |
            aws sns publish \
              --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
              --message "Backup Failed for repository: ${{ github.repository }} – Workflow: ${{ github.workflow }} – Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
              --subject "Backup Failed: ${{ github.repository }}"
