name: Mirror repo to S3
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1.1.1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          MIRROR_TARGET: backup-git-trinks-prd/${{ github.event.repository.name }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY_PROD }}
        with:
          args: --overwrite --remove
